services:

  movie_db:
    image: postgres:17.4
    container_name: movie_db
    environment:
      TZ: Europe/Tallinn
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
      POSTGRES_DB: movie
    volumes:
      - movie_db_data:/var/lib/postgresql/data
    ports:
      - "5499:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  keycloak_db:
    image: postgres:17.4
    container_name: keycloak_db
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      TZ: Europe/Tallinn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5441:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/movie-realm.json
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL_DATABASE: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_PORT: 5432
    ports:
      - "8888:8080"
    volumes:
      - ./movie-realm.json:/opt/keycloak/data/import/movie-realm.json
    command: start-dev --import-realm
    restart: unless-stopped

  movie_redis:
    container_name: movie_redis
    image: redis:8.0-M03-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass changeme

volumes:
  movie_db_data:
  movie_redis_data:
  keycloak_db_data:
  keycloak_data:
