services:

  movie_db:
    container_name: movie_db
    image: postgres:16
    environment:
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
      POSTGRES_DB: movie
    volumes:
      - movie_db_data:/var/lib/postgresql/data
    ports:
      - 5499:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  movie_redis:
    container_name: movie_redis
    image: redis:8.0-M03-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass changeme

volumes:
  movie_db_data:
  movie_redis_data:
