services:

  movie-backend-db:
    container_name: movie-backend-db
    image: postgres:16
    environment:
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
      POSTGRES_DB: movie
    volumes:
      - movie-backend-db:/var/lib/postgresql/data
    ports:
      - 5499:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  movie-backend-db:
