spring:
  application:
    name: movie-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5499/movie?autoreconnect=true
    username: movie
    password: movie

  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
